// Type definitions for the ScheduleIt platform
// Full types will be generated by Prisma in Task 2

export type BookingStatus = "PENDING" | "CONFIRMED" | "CANCELLED" | "RESCHEDULED" | "COMPLETED";

export type EventTypeCategory = "ONE_ON_ONE" | "GROUP" | "ROUND_ROBIN" | "COLLECTIVE";

export type MeetingLocationType = "GOOGLE_MEET" | "ZOOM" | "TEAMS" | "PHONE" | "IN_PERSON" | "CUSTOM";

export type DayOfWeek = "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";

export type TeamMemberRole = "OWNER" | "ADMIN" | "MEMBER";

export interface TimeSlot {
  start: string; // ISO string
  end: string;   // ISO string
  available: boolean;
}

export interface AvailabilityDay {
  day: DayOfWeek;
  enabled: boolean;
  startTime: string; // "HH:mm"
  endTime: string;   // "HH:mm"
}
